# -*- coding: utf-8 -*-
"""generativeAI(translation).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19K7NzzbUD7aLqR82UkEKTXSAu997mcPe
"""

# 1. Install Hugging Face Transformers
!pip install transformers sentencepiece

# 2. Import libraries
from transformers import MarianMTModel, MarianTokenizer, pipeline

# --- Models ---
def cargar_modelo(origen, destino):
    # Avalaible models of Helsinki-NLP (translation)
    model_name = f"Helsinki-NLP/opus-mt-{origen}-{destino}"
    tokenizer = MarianTokenizer.from_pretrained(model_name)
    model = MarianMTModel.from_pretrained(model_name)
    return pipeline("translation", model=model, tokenizer=tokenizer)

# --- translate with style ---
def traducir(texto, origen="es", destino="en", estilo="neutral"):
    traductor = cargar_modelo(origen, destino)
    traduccion = traductor(texto, max_length=100)[0]['translation_text']

    # Simple prompts to adapt to the style
    if estilo == "formal":
        traduccion = f"Formally expressed: {traduccion}"
    elif estilo == "coloquial":
        traduccion = f"Casual tone: {traduccion}"
    elif estilo == "literario":
        traduccion = f"Poetic version: {traduccion}"

    return traduccion

# --- Examples ---
texto1 = "Buenos días, ¿cómo estás?"
texto2 = "Estoy muy cansado después de estudiar tanto."
texto3 = "La tecnología puede cambiar el futuro."

print("Ejemplo 1:", traducir(texto1, "es", "en", estilo="formal"))
print("Ejemplo 2:", traducir(texto2, "es", "fr", estilo="coloquial"))
print("Ejemplo 3:", traducir(texto3, "es", "en", estilo="literario"))